image: Visual Studio 2017

environment:
  MSYS2_DIR: msys64

  matrix:
    - MSYSTEM: MINGW64
      myarch: x86_64callbacks

build_script:
- del C:\Windows\System32\libssl-*.dll C:\Windows\system32\libcrypto-*.dll
- del C:\Windows\SysWOW64\libssl-*.dll C:\Windows\SysWOW64\libcrypto-*.dll
- cmd: >-
    cd %APPVEYOR_BUILD_FOLDER%

    @echo on

    SET "PATH=C:\%MSYS2_DIR%\%MSYSTEM%\bin;C:\%MSYS2_DIR%\usr\bin;%PATH%"

    git clone --recursive https://github.com/loganmc10/m64p.git
    
    cd m64p
    
    bash -c "rm -rf GLideN64 && git clone --depth=1 https://github.com/tim241/GLideN64/ -b m64p-gui"
    
    bash -c "pacman -Syu --noconfirm"

    bash -c "pacman -S --needed --noconfirm git mingw-w64-$myarch-nasm mingw-w64-$myarch-freetype mingw-w64-$myarch-libpng mingw-w64-$myarch-libsamplerate mingw-w64-$myarch-SDL2 mingw-w64-$myarch-jasper mingw-w64-$myarch-qt5 zip"
    
    bash -c "chmod +x ../build.sh"
        
    bash -c "export HOST_CPU=$myarch; ../build.sh"

artifacts:
   - path: m64p\mupen64plus-GLideN64-win64.zip
     name: mupen64plus-GLideN64-win64.zip
