version: 1.0.{build}
image: Visual Studio 2017
clone_folder: c:\mg
environment:
  MSYS2_DIR: msys64
  ACCESS_KEY:
    secure: 4U3SfYBNNlc0VXB/9kPvqFH0qbzOD3FXHIY7SuRFvcQ=
  SECRET_KEY:
    secure: PtL0a/tSy8HJbUiwu8GNvx+UfOeOiSTrqGxmGswskxs8EBVLIJX5k2LgnX85V45G

  matrix:
    - MSYSTEM: MINGW64
      myarch: x86_64

build_script:
- del C:\Windows\System32\libssl-*.dll C:\Windows\system32\libcrypto-*.dll
- del C:\Windows\SysWOW64\libssl-*.dll C:\Windows\SysWOW64\libcrypto-*.dll
- cmd: >-
    cd %APPVEYOR_BUILD_FOLDER%

    @echo on

    SET "PATH=C:\%MSYS2_DIR%\%MSYSTEM%\bin;C:\%MSYS2_DIR%\usr\bin;%PATH%"

    git clone --recursive https://github.com/loganmc10/m64p.git
    
    bash -c "pacman -Syu --noconfirm"

    bash -c "pacman -S --needed --noconfirm mingw-w64-$myarch-nasm mingw-w64-$myarch-freetype mingw-w64-$myarch-libpng mingw-w64-$myarch-libsamplerate mingw-w64-$myarch-SDL2 mingw-w64-$myarch-jasper mingw-w64-$myarch-qt5 zip"

    cd %APPVEYOR_BUILD_FOLDER%\m64p
    
    bash -c "chmod +x ../build.sh"

    bash -c "export HOST_CPU=$myarch; ../build.sh"


artifacts:
   - path: m64p\mupen64plus-GLideN64-win64.zip
     name: mupen64plus-GLideN64-win64.zip
