image: Visual Studio 2017

environment:
  MSYS2_DIR: msys64

  matrix:
    - MSYSTEM: MINGW64
      myarch: x86_64

build_script:
- del C:\Windows\System32\libssl-*.dll C:\Windows\system32\libcrypto-*.dll
- del C:\Windows\SysWOW64\libssl-*.dll C:\Windows\SysWOW64\libcrypto-*.dll
- cmd: >-
    cd %APPVEYOR_BUILD_FOLDER%

    @echo on

    SET "PATH=C:\%MSYS2_DIR%\%MSYSTEM%\bin;C:\%MSYS2_DIR%\usr\bin;%PATH%"

    git clone https://github.com/Rosalie241/m64p
    
    cd m64p
    
    git checkout a559892e4779b4f8f1d9d0d8a9219e067b1c7e19
    
    git submodule update --init --recursive
        
    bash -c "curl -O http://repo.msys2.org/msys/x86_64/msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz && curl -O http://repo.msys2.org/msys/x86_64/msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz.sig && pacman -U --noconfirm --config <(echo) msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz"
        
    bash -c "rm -rf GLideN64 && git clone --depth=1 https://github.com/Rosalie241/GLideN64/ -b m64p-gui"
    
    bash -c "pacman -Sy zstd --noconfirm"
    
    bash -c "pacman -Syu --noconfirm"

    bash -c "pacman -S --needed --noconfirm git mingw-w64-$myarch-nasm mingw-w64-$myarch-freetype mingw-w64-$myarch-libpng mingw-w64-$myarch-libsamplerate mingw-w64-$myarch-SDL2 mingw-w64-$myarch-jasper mingw-w64-$myarch-qt5 zip"
    
    bash -c "chmod +x ../build.sh"
        
    bash -c "export HOST_CPU=$myarch; ../build.sh"

artifacts:
   - path: m64p\mupen64plus-GLideN64-win64.zip
     name: mupen64plus-GLideN64-win64.zip
